package sys.model;
// Generated 15/09/2023 11:12:03 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idUser;
     private String firstName;
     private String lastName;
     private String mail;
     private String password;

    public Users() {
    }

	
    public Users(String mail, String password) {
        this.mail = mail;
        this.password = password;
    }
    public Users(String firstName, String lastName, String mail, String password) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.mail = mail;
       this.password = password;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


